### ISSUE TITLE
Yo

### ISSUE THREAD

**Issue by lindxhimeko** [adilhyz/ArchLinux#2]
tefuc
![f816c707f46fad40a7051a86f7b48823c2c55f3fe8c855bd938e14e9e0ddad23](https://github.com/adilhyz/ArchLinux/assets/120332564/b952cbb6-3bf9-423a-95e7-02ae111eb4a8)

**Comment by adilhyz** [comment]
> tefuc ![f816c707f46fad40a7051a86f7b48823c2c55f3fe8c855bd938e14e9e0ddad23](https://user-images.githubusercontent.com/120332564/263682735-b952cbb6-3bf9-423a-95e7-02ae111eb4a8.gif)

:angry: stop that
