### ISSUE TITLE
Waduh

### ISSUE THREAD

**Issue by lindxhimeko** [adilhyz/ArchLinux#3]
Hudaw
![a332d9f0b4eff149b6a319f1b73b7ed478cb962ceb9add9d9f73c5f20d07c21f](https://github.com/adilhyz/ArchLinux/assets/120332564/42ce8fda-5c59-4afe-9619-d35476694cd5)

**Comment by adilhyz** [comment]
> Hudaw ![a332d9f0b4eff149b6a319f1b73b7ed478cb962ceb9add9d9f73c5f20d07c21f](https://user-images.githubusercontent.com/120332564/263682859-42ce8fda-5c59-4afe-9619-d35476694cd5.gif)

wtf are u  doing?
